---
- name: Verify sshd_config settings
  hosts: localhost
  become: yes
  tasks:
    - name: Check settings in sshd_config
      ansible.builtin.command:
        cmd: "grep -E '^{{ item.key }}\s+{{ item.value }}$' /etc/ssh/sshd_config"
      loop:
        - { key: "PrintLastLog", value: "yes" }
        - { key: "StrictModes", value: "yes" }
        - { key: "X11Forwarding", value: "no" }
        - { key: "IgnoreUserKnownHosts", value: "yes" }
        - { key: "IgnoreRhosts", value: "yes" }
        - { key: "KerberosAuthentication", value: "no" }
        - { key: "GSSAPIAuthentication", value: "no" }
      loop_control:
        label: "{{ item.key }}"
      register: check_results
      ignore_errors: yes

    - name: Show verification results
      ansible.builtin.debug:
        msg: "Verification for {{ item.item.key }}: {{ 'PASSED' if item.rc == 0 else 'FAILED' }}"
      loop: "{{ check_results.results }}"
      loop_control:
        label: "{{ item.item.key }}"
